// /*  Project nGenEx	Fractal Dev Games	Copyright (C) 2024. All Rights Reserved.	SUBSYSTEM:    SSW	FILE:         Game.cpp	AUTHOR:       Carlos Bott*/


#include "CampaignSubsystem.h"

// Timer Subsystem
#include "TimerSubsystem.h"

// Planner headers
#include "CampaignPlanner.h"
#include "PlannerStrategic.h"
#include "PlannerAssignment.h"
#include "PlannerMovement.h"
#include "PlannerMission.h"
#include "PlannerEvent.h"

void UCampaignSubsystem::Initialize(FSubsystemCollectionBase& Collection)
{
	Super::Initialize(Collection);

	// Subscribe to your master clock tick:
	if (UTimerSubsystem* Timer = GetGameInstance()->GetSubsystem<UTimerSubsystem>())
	{
		// Expected signature: (int64 NowSeconds, int64 DeltaSeconds)
		Timer->OnUniverseSecond.AddUObject(this, &UCampaignSubsystem::HandleUniverseSecond);
	}

	BuildPlanners();

	UE_LOG(LogTemp, Log, TEXT("[CampaignSubsystem] Initialized"));
}

void UCampaignSubsystem::Deinitialize()
{
	StopCampaign();

	if (UTimerSubsystem* Timer = GetGameInstance()->GetSubsystem<UTimerSubsystem>())
	{
		Timer->OnUniverseSecond.RemoveAll(this);
	}

	Planners.Empty();
	MissionOffers.Empty();

	UE_LOG(LogTemp, Log, TEXT("[CampaignSubsystem] Deinitialized"));
	Super::Deinitialize();
}

void UCampaignSubsystem::BuildPlanners()
{
	Planners.Empty();

	// Cadences (seconds) - tune later:
	// Strategic: 60s
	// Assignment: 300s
	// Movement: 7200s
	// Mission: 1s
	// Event: 300s
	Planners.Add(MakeUnique<FPlannerStrategic>(*this, 60));
	Planners.Add(MakeUnique<FPlannerAssignment>(*this, 300));
	Planners.Add(MakeUnique<FPlannerMovement>(*this, 7200));
	Planners.Add(MakeUnique<FPlannerMission>(*this, 1));
	Planners.Add(MakeUnique<FPlannerEvent>(*this, 300));

	UE_LOG(LogTemp, Log, TEXT("[CampaignSubsystem] Built %d planners"), Planners.Num());
}

void UCampaignSubsystem::ResetPlanners(int64 NowSeconds)
{
	for (TUniquePtr<ICampaignPlanner>& Planner : Planners)
	{
		Planner->Reset(NowSeconds);
	}
}

void UCampaignSubsystem::HydrateFromDataTables()
{
	// Stub for now:
	// - Later, load DT rows into plain C++ caches here
	// - Do NOT touch DTs inside planners
	UE_LOG(LogTemp, Log, TEXT("[CampaignSubsystem] HydrateFromDataTables (stub)"));
}

void UCampaignSubsystem::StartCampaign(int32 CampaignId)
{
	ActiveCampaignId = CampaignId;
	bRunning = true;

	Rng.Initialize(FMath::Rand());

	NextOfferId = 1;
	ClearMissionOffers();

	bHasActiveCampaign = false;
	if (!LoadActiveCampaignRowByIndex(CampaignId))
	{
		UE_LOG(LogTemp, Error, TEXT("[CampaignSubsystem] StartCampaign failed (no campaign row)"));
		bRunning = false;
		ActiveCampaignId = -1;
		return;
	}

	ResetPlanners(LastNowSeconds);

	// Starshatter rule: Campaign 1 is training; 2+ is dynamic.
	// Data-driven fallback: if TemplateList exists, treat as dynamic.
	const bool bHasTemplates = ActiveCampaignConfig.TemplateList.Num() > 0;

	if (CampaignId == 1 && !bHasTemplates)
	{
		BuildTrainingOffers();  // Ops can display immediately
	}
	else
	{
		// Dynamic: let PlannerMission generate offers on tick
		UE_LOG(LogTemp, Log, TEXT("[CampaignSubsystem] Dynamic campaign: offers will be generated by planners."));
	}

	UE_LOG(LogTemp, Log, TEXT("[CampaignSubsystem] StartCampaign id=%d"), ActiveCampaignId);
}

void UCampaignSubsystem::StopCampaign()
{
	if (!bRunning)
		return;

	UE_LOG(LogTemp, Log, TEXT("[CampaignSubsystem] StopCampaign id=%d"), ActiveCampaignId);

	bRunning = false;
	ActiveCampaignId = -1;
}

void UCampaignSubsystem::HandleUniverseSecond(uint64 UniverseSeconds)
{
	if (!bRunning)
		return;

	uint64 DeltaSeconds = 1;

	if (!bHasLastUniverseSeconds)
	{
		bHasLastUniverseSeconds = true;
		LastUniverseSeconds = UniverseSeconds;
		DeltaSeconds = 1;
	}
	else
	{
		// Handle missed ticks gracefully:
		DeltaSeconds = (UniverseSeconds > LastUniverseSeconds)
			? (UniverseSeconds - LastUniverseSeconds)
			: 0;

		LastUniverseSeconds = UniverseSeconds;
	}

	FCampaignTickContext Ctx;
	Ctx.NowSeconds = (int64)UniverseSeconds;
	Ctx.DeltaSeconds = (int64)DeltaSeconds;
	Ctx.Rng = &Rng;

	for (TUniquePtr<ICampaignPlanner>& Planner : Planners)
	{
		Planner->TickCampaign(Ctx);
	}
}

int32 UCampaignSubsystem::AllocateOfferId()
{
	return NextOfferId++;
}

void UCampaignSubsystem::AddMissionOffer(FMissionOffer Offer)
{
	MissionOffers.Add(MoveTemp(Offer));
	OnMissionOffersChanged.Broadcast();
}

void UCampaignSubsystem::ClearMissionOffers()
{
	MissionOffers.Reset();
	OnMissionOffersChanged.Broadcast();
}

bool UCampaignSubsystem::LoadActiveCampaignRowByIndex(int32 CampaignIndex)
{
	if (!CampaignDT)
	{
		UE_LOG(LogTemp, Error, TEXT("[CampaignSubsystem] CampaignDT is null. Call SetCampaignDataTable() first."));
		return false;
	}

	// DataTables are keyed by RowName, but your FS_Campaign has Index.
	// We therefore scan rows once per campaign start.
	TArray<FS_Campaign*> Rows;
	CampaignDT->GetAllRows(TEXT("LoadActiveCampaignRowByIndex"), Rows);

	for (const FS_Campaign* Row : Rows)
	{
		if (Row && Row->Index == CampaignIndex)
		{
			ActiveCampaignConfig = *Row;   // copy snapshot
			bHasActiveCampaign = true;

			UE_LOG(LogTemp, Log, TEXT("[CampaignSubsystem] Loaded campaign '%s' Index=%d  Missions=%d  Templates=%d  Actions=%d"),
				*ActiveCampaignConfig.Name,
				ActiveCampaignConfig.Index,
				ActiveCampaignConfig.MissionList.Num(),
				ActiveCampaignConfig.TemplateList.Num(),
				ActiveCampaignConfig.Action.Num());

			return true;
		}
	}

	UE_LOG(LogTemp, Error, TEXT("[CampaignSubsystem] No campaign row found with Index=%d"), CampaignIndex);
	return false;
}

void UCampaignSubsystem::BuildTrainingOffers()
{
	ClearMissionOffers();

	// Campaign 1 training missions are the “static missions.def equivalent”
	for (const FS_CampaignMissionList& M : ActiveCampaignConfig.MissionList)
	{
		if (!M.Available || M.Complete)
			continue;

		FMissionOffer Offer;
		Offer.OfferId = AllocateOfferId();

		// For training missions, this is not a template row; store the mission name/id as a tag.
		Offer.MissionTemplateRow = NAME_None;
		Offer.StartTimeSeconds = LastNowSeconds;
		Offer.SourceTag = FString::Printf(TEXT("TRAINING:%d:%s"), M.Id, *M.Name);

		AddMissionOffer(MoveTemp(Offer));
	}

	UE_LOG(LogTemp, Log, TEXT("[CampaignSubsystem] Training offers built: %d"), MissionOffers.Num());
}







